# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0003_auto_20170609_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
