# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0004_auto_20170609_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_short_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
