# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0005_auto_20170609_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_short_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
