# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0007_auto_20170609_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='words_audio'),
        ),
    ]
