# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0008_word_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_name_short', models.CharField(max_length=25)),
                ('test_visible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_thumbnails')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_short_name',
            new_name='category_name_short',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word_short_name',
            new_name='word_name_short',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_thumbnails'),
        ),
    ]
