# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0010_auto_20170612_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFourImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(verbose_name='date taken')),
                ('finished', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slovnik.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TestFourImagesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slovnik.TestFourImages')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_word', to='slovnik.Word')),
                ('word_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_word', to='slovnik.Word')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TestVariant',
        ),
        migrations.AddField(
            model_name='testfourimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slovnik.User'),
        ),
    ]
