# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0011_auto_20170619_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfourimagesitem',
            name='word_other_first',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='word_other_one', to='slovnik.Word'),
        ),
        migrations.AddField(
            model_name='testfourimagesitem',
            name='word_other_second',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='word_other_two', to='slovnik.Word'),
        ),
        migrations.AddField(
            model_name='testfourimagesitem',
            name='word_other_third',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='word_other_three', to='slovnik.Word'),
        ),
        migrations.AddField(
            model_name='testfourimagesitem',
            name='word_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testfourimagesitem',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_given', to='slovnik.Word'),
        ),
        migrations.AlterField(
            model_name='testfourimagesitem',
            name='word_selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_selected', to='slovnik.Word'),
        ),
    ]
