# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0012_auto_20170626_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfourimagesitem',
            name='word',
        ),
        migrations.AddField(
            model_name='testfourimagesitem',
            name='word_correct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_correct', to='slovnik.Word'),
        ),
        migrations.AlterField(
            model_name='testfourimagesitem',
            name='word_other_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_other_one', to='slovnik.Word'),
        ),
        migrations.AlterField(
            model_name='testfourimagesitem',
            name='word_other_second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_other_two', to='slovnik.Word'),
        ),
        migrations.AlterField(
            model_name='testfourimagesitem',
            name='word_other_third',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_other_three', to='slovnik.Word'),
        ),
        migrations.AlterField(
            model_name='testfourimagesitem',
            name='word_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_selected', to='slovnik.Word'),
        ),
    ]
