# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0014_auto_20170626_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfourimagesitem',
            name='word_correct_position',
            field=models.IntegerField(default=0),
        ),
    ]
