# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0015_testfourimagesitem_word_correct_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=100)),
                ('choice2', models.CharField(max_length=100)),
                ('choice3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RatingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rating_images')),
            ],
        ),
        migrations.CreateModel(
            name='RatingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ratingchoices',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slovnik.RatingImages'),
        ),
        migrations.AddField(
            model_name='ratingchoices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slovnik.RatingUser'),
        ),
    ]
