# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0016_auto_20170628_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingimages',
            name='name',
            field=models.CharField(default='asd', max_length=15),
        ),
    ]
