# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0017_ratingimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingimages',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
