# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0018_auto_20170630_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinguser',
            name='password',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
