# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovnik', '0019_ratinguser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingchoices',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ratingchoices',
            name='choice2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratingchoices',
            name='choice3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
